#!/usr/bin/env bash
# by Kaasu

HASH=$1

curl --silent 'http://getkaasu.info/daemon/json_rpc' --data '{"jsonrpc":"2.0","id":"test","method":"f_transaction_json","params":{"hash":"'"$HASH"'"}}' --compressed | jq '.result.tx.extra' | xxd -r -p













